name: Backfill listeners

on:
  workflow_dispatch: {}   # spustíš ručne v GitHub → Actions

jobs:
  backfill:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run backfill
        env:
          OUT_PATH: data/playlist.json
        run: python backfill_listeners.py
      - name: Commit & push JSON if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/playlist.json
          git commit -m "backfill listeners" || exit 0
          git push
