name: Enrich metadata
on:
  schedule:
    - cron: "15 2 * * *"   # denne 02:15
  workflow_dispatch: {}
jobs:
  enrich:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run enrichment
        env:
          PLAYLIST_PATH: data/playlist.json
          CACHE_PATH: data/meta_cache.json
        run: python enrich_metadata.py
      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/playlist.json data/meta_cache.json
          git commit -m "enrich: update metadata" || exit 0
          git push
