name: Keep Render awake

on:
  schedule:
    - cron: "*/5 * * * *"   # každých 10 min
  workflow_dispatch: {}       # možnosť spustiť ručne

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render /health
        run: |
          curl -fsS https://melody-now.onrender.com/health > /dev/null || true
