name: Scrape Melody Playlist (history)

on:
  schedule:
    - cron: "*/5 * * * *"   # každých 5 min
  workflow_dispatch: {}

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run scraper
        env:
          OUT_PATH: data/playlist.json
        run: python scrape_melody.py
      - name: Commit & push JSON if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/playlist.json
          git commit -m "update playlist" || exit 0
          git push
